version: '3.8'
services:
  ndt-db:
    image: postgres:14.1-alpine
    container_name: ndt-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  ndt-api:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: ndt-api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: retronova-db
      POSTGRES_PORT: 5432
    depends_on:
      ndt-db:
        condition: service_healthy
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app

volumes:
  pgdata:
