name: Prod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TAG: 'prod'
  IMAGE_NAME: "ndt-api"
  CONTAINER_NAME: "ndt-api"
  PORT: 8000

  DATABASE_URL: ${{ vars.DATABASE_URL_PROD }}
  DATABASE_USER: ${{ vars.DATABASE_USER_PROD }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD_PROD }}
  DATABASE_NAME: ${{ vars.DATABASE_NAME_PROD }}

jobs:

  stop:
    runs-on: prod
    steps:
      - uses: actions/checkout@v3
      - name: stop
        run: |
          docker stop $CONTAINER_NAME || true
          docker compose down
          
  deploy:
    runs-on: prod
    needs: [stop]
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          docker compose up

  cleanup:
    runs-on: prod
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3
      - name: cleanup
        run: |
          docker image prune -f
          docker container prune -f
